##########
# collectionbuilder-contentdm
# Jekyll Digital Collection Generator, designed as a skin over CONTENTdm
# https://github.com/CollectionBuilder/collectionbuilder-contentdm
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://cdil.lib.uidaho.edu
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /wilderness-hearings
# location of code, the full url to your github repository
source-code: https://github.com/thecdil/wilderness-hearings

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Idaho Wilderness Hearings
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Public Statements Presented to U.S. Senate in 1983
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Idaho wilderness hearings before the Subcommittee on Public Lands and Reserved Water of the Committee on Energy and Natural Resources, United States Senate, Ninety-eighth Congress, first session, to review the Idaho wilderness recommendations." 
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: evanwill; owikle
# Organization branding
organization-name: "Center for Digital Inquiry and Learning (CDIL), University of Idaho Library"
organization-link: https://cdil.lib.uidaho.edu/
organization-logo-banner: /assets/img/cdil.png
organization-logo-nav: /assets/img/ui-library.png


##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: statement-entities
# contentdm collection name, matches collection ID used by CDM
# cdm-collection-id: psychiana
# CONTENTdm server url
# cdm-url: https://digital.lib.uidaho.edu
# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: 'statement-entities'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
